INSERT INTO console_manufacturer (name) VALUES('Nintendo');
INSERT INTO console_manufacturer (name) VALUES('Sega');
INSERT INTO console_manufacturer (name) VALUES('Sony');
INSERT INTO console_manufacturer (name) VALUES('Commodore');
INSERT INTO console_manufacturer (name) VALUES('Sinclair');

INSERT INTO console_console (name, description, price, manufacturer_id) VALUES('Super NES Classic', 'The Super NES Classic Edition system looks and feels just like the original 90s home console, except it’s super small. Two wired Super NES Classic Controllers are included for instant multiplayer action. Just plug it in and play!', 119.95, 1);
INSERT INTO console_console (name, description, price, manufacturer_id) VALUES('Sega Genesis', 'The iconic SEGA Genesis console that defined a generation of gaming returns in a slick, miniaturized unit. Included are two wired controllers.', 69.99, 2);
INSERT INTO console_console (name, description, price, manufacturer_id) VALUES('NES Classic', 'The NES Classic Edition system is a miniaturized version of the groundbreaking NES, originally released in 1985. Just plug the NES Classic Edition into your TV, pick up that gray controller, and rediscover the joy of NES games. Included is one NES Classic Controller.', 59.99, 1);
INSERT INTO console_console (name, description, price, manufacturer_id) VALUES('Playstation Classic', 'A miniature recreation of the original PlayStation. The design of PlayStation Classic perfectly mirrors the original console, with the same logo, button layout and packaging – but 45% smaller than 1994’s PlayStation. This miniature console comes  with an HDMI cable to connect to your TV complete with two wired controllers, plus a virtual memory card to save your adventures as you switch between titles.', 99.99, 3);
INSERT INTO console_console (name, description, price, manufacturer_id) VALUES('Commodore 64', 'The World’s Best-Selling Home Computer – Re-reborn. The C64 is back, this time full-sized with a working keyboard for the dedicated retro home-computer fan. Included along with the C64 Home Computer is a full-size working keyboard and a micro-switch USB joystick.', 88.99, 4);
INSERT INTO console_console (name, description, price, manufacturer_id) VALUES('Game Boy', 'Everyone loves Game Boy. Packing a huge amount of power into a tiny package, this little console proved a revolution in videogaming when it launched in Japan in 1989. Since then, this pocket-sized system has sold over 100 million units, giving gamers all over the world the freedom to play their favourite games no matter where they are.', 59.95, 1);
INSERT INTO console_console (name, description, price, manufacturer_id) VALUES('ZX Spectrum', 'One of the most popular home computers ever made. ', 68.95, 5);

INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/uAWG3pRKr7TRTr6X6', 1);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/b8JYMnhkdco9eEpy8', 1);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/mmqBm8U8EiHecYZL8', 1);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/Ybzqe2fQxiy1u9mdA', 2);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/7LA1nUohYuggcQyQ8', 2);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/PFqFgYe5RgqVfxTg8', 2);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/z6YwwKovveiq52m79', 3);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/3mxZLJFU74bnRUbp6', 3);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/WMm2HUdg1cP3RuxJA', 4);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/vY136NZ33VskMuG3A', 4);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/DoBVyQBhrow1Kyoy6', 4);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/yo2ggwZdXXLmWgZ18', 5);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/pStKPC8WHJbmgoGYA', 5);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/Pi6KKggCXwiFxmvo8', 6);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/CbC9p497CgLjks3E7', 6);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/R8fLgLC2E69QTAUh8', 7);
INSERT INTO console_consoleimage (image, console_id) VALUES('https://images.app.goo.gl/XYZPTcZXJkxTuBzS8', 7);

INSERT INTO game_gamegenre (name) VALUES('Platform');
INSERT INTO game_gamegenre (name) VALUES('Arcade');
INSERT INTO game_gamegenre (name) VALUES('Racing');
INSERT INTO game_gamegenre (name) VALUES('Adventure');
INSERT INTO game_gamegenre (name) VALUES('Sports');
INSERT INTO game_gamegenre (name) VALUES('Puzzle');
INSERT INTO game_gamegenre (name) VALUES('Action');

INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Super Mario World', 'Super Mario World is a 1990 side-scrolling platform game developed and published by Nintendo for the Super Nintendo Entertainment System. The story follows Marios quest to save Princess Toadstool and Dinosaur Land from the series antagonist Bowser and his minions, the Koopalings.', 15.99, 1990, 'Nintendo', 1, [1]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Donkey Kong Country', 'Donkey Kong Country is a platforming game in which the player guides protagonists Donkey Kong (DK) and Diddy Kong (Diddy) through 40 side-scrolling levels. DK and Diddy are the games main characters and the only playable characters. The player can switch between Kongs if both characters are present.', 18.99, 1994, 'Nintendo', 1, [1]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Sonic the Hedgehog', 'Sonic is a blue anthropomorphic hedgehog who can run at supersonic speeds and curl into a ball, primarily to attack enemies. Sonic must race through levels, collecting power-up rings and avoiding obstacles and enemies.', 9.49, 1991, 'Sega', 2, 1);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Sonic the Hedgehog 2', 'Sonic the Hedgehog 2 is a 2D side-scrolling platform game. The game stars Sonic the Hedgehog and his sidekick, Miles "Tails" Prower, who is described as having idolized Sonic as a child and wanting to keep up with him. At the games start, the player can select to either play as Sonic, Tails, or both.', 9.49, 1992, 'Sega', 2, [1]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Pac-Man', 'Pac-Man is a maze chase video game. The player controls the titular character through an enclosed maze; the objective of the game is to eat all of the dots placed in the maze while avoiding four colored ghosts — Blinky (red), Pinky (pink), Inky (cyan), and Clyde (orange) — that pursue him.', 12.49, 1980, 'Namco', 3, [2]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Super Mario Bros. 3', 'The plot of Super Mario Bros. 3 is described in the instruction booklet. The Mushroom World, the setting of the game, is invaded by the Koopalings, Bowsers seven children. The Koopalings conquer each of the seven kingdoms by stealing its kings magical wand and using it to transform him into an animal.', 11.99, 1988, 'Nintendo', 3, [1]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('R4: Ridge Racer Type 4', 'R4: Ridge Racer Type 4 is an arcade-style racing game with a strong emphasis on powersliding around corners. Vehicles use one of two styles of powersliding depending on the make of car they select: Drift and Grip. ... Vehicles are earned by playing through the games Grand Prix mode.', 29.49, 1998, 'Namco', 4, [3]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Crash Bandicoot', 'Crash is a mutant eastern barred bandicoot who was genetically enhanced by the series main antagonist Doctor Neo Cortex and soon escaped from Cortexs castle after a failed experiment in the "Cortex Vortex". The story follows Crash as he aims to prevent Brio and Cortexs plans for world domination, and rescue his girlfriend Tawna, a female bandicoot also evolved by Brio and Cortex.', 34.95, 1996, 'Naughty Dog', 4, [1,3]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Impossible Mission', 'The player takes the role of a secret agent who must stop an evil genius, Professor Elvin Atombender, who is believed to be tampering with national security computers. The player races against the clock to reassemble and decrypt the password to Atombenders control room while avoiding deadly robots.', 24.99, 1984, 'Epyx', 5, [1,4]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('California Games', 'Branching from their popular Summer Games and Winter Games series, this game consists of a collection of outdoor sports purportedly popular in California. Sports include Half-Pipe, Roller-skating and surfing among others.', 26.99, 1987, 'Epyx', 5, [5]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Tetris', 'The game has a simple goal of destroying lines of block before it reaches the top. The line is made up of a square block. Tetrominoes is the shape of the 4 connected blocks that falls vertically down.', 12.49, 1989, 'Nintendo', 6, [6]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Kirbys Dream Land', 'Kirby and Gooey are on a fishing trip, when all of a sudden, Dark Matter appears and shatters the planets rings. He then proceeds to possess various Dream-Landers, including King Dedede. Kirby and Gooey then team up with Rick, Coo, and Kine, as well as new characters Pitch, ChuChu, and Nago.', 14.95, 1992, 'HAL Laboratory', 6, [1,7]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Manic Miner', 'The first game in the Miner Willy series and among the early titles in the platform game genre. In each of the twenty caverns, each one screen in size, are several flashing objects, which the player must collect before Willys oxygen supply runs out.', 22.39, 1983, 'Matthew Smith', 7, [1]);
INSERT INTO game_game (name, description, price, release_year, developer, console_id, genre_id) VALUES('Jet Set Willy', 'Jet Set Willy is a flip-screen platform game in which the player moves the protagonist, Willy, from room to room in his mansion collecting objects. Unlike the screen-by-screen style of its prequel, the player can explore the mansion at will. Willy is controlled using only left, right and jump.', 25.99, 1984, 'Matthew Smith', 7, [1]);

INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/eM5599Wgx2zEbWG17', 1);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/HKvYgsGBw3qCLkr19', 1);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/km8G766CKwSCSu1WA', 1);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/rhot8dM5s4cqreTf8', 2);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/8bgsHNEXTKJBTh8d9', 2);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/UpC8WYeD4nQPCotn9', 2);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/rj4fn57qNd9eQCVh9', 3);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/wqru9BE52ZowBTT66', 3);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/sWyyY16NosBshFyh9', 3);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/K4kqq4gRGsD8vBgHA', 4);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/3XXeUgkAMiP1YjZX9', 4);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/SqRGRnDCo6ohaQPq5', 4);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/hfhvcpJxEhbJqtPp8', 5);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/YdkAkNtfE5J5xaPh8', 5);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/JZjqGKeLNEcL1Ke36', 5);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/oLULGbib6L6AN7y19', 6);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/b91SQ1Xpy9phTnLx7', 6);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/FxbBf9cwR6qnFmqU9', 6);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/JARXU7Rjy336mNmJA', 7);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/K5RnEmKctNsVUVTL9', 7);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/b3nPuFPD3wavyF5S8', 8);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/3B3szcV2j3C9TQ8F7', 8);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/jsNyS916TFAii3ts8', 9);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/eXG1iUdwyUotkVJt9', 9);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/cBkuWmGG64sZwGHV9', 9);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/7ULWEECh8Ua2Tbid6', 10);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/DgzC1RUXzwi45Kpd8', 10);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/Ujy57XuLe57wc5wk9', 10);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/hwt55a8CkWNyKLhz6', 11);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/TcpuSDnn2ZyKVfVD6', 11);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/Py1gLr3QjJpKN27M9', 11);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/qkonft2FatscELDE9', 12);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/y2AiKhCzjyP7DuSa8', 12);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/H1cdRXb7jf6bSqZCA', 12);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/PbyjoMiURshUiQRm8', 13);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/w1sZ5o2cC1TG3g8W8', 13);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/X9HWKQLjNc7Hp2F98', 14);
INSERT INTO game_gameimage (image, game_id) VALUES('https://images.app.goo.gl/F9QLc56tQyb4MS179', 14);
